/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package journalapplication;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
/**
 *
 * @author pranav
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    public FrontPage() {
        initComponents();
        try{
            Class.forName("oracle.jdbc.OracleDriver");
           // JOptionPane.showMessageDialog(this,"Driver Loaded!");
            try {
            con = DriverManager.getConnection("jdbc:oracle:thin:@10.211.55.3:1521:orcl",
                    "scott","tiger");
          //  JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
            }
            catch (SQLException ex) {
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
            }
            }
            catch(ClassNotFoundException ex){
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());

            } 
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        journalPopup = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        projectLogo = new javax.swing.JLabel();
        projectTitle = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        journalPanel = new javax.swing.JPanel();
        journals = new javax.swing.JButton();
        bottomImage = new javax.swing.JLabel();
        conferencesPanel = new javax.swing.JPanel();
        conferences = new javax.swing.JButton();
        organizationsPanel = new javax.swing.JPanel();
        organizations = new javax.swing.JButton();
        articlesPanel = new javax.swing.JPanel();
        articles = new javax.swing.JButton();

        jMenuItem1.setText("View Journals");
        journalPopup.add(jMenuItem1);

        jMenuItem2.setText("Create Journal");
        journalPopup.add(jMenuItem2);

        jMenuItem3.setText("View Conferences");
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projectLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/journalapplication/dbmslogo (1).jpeg"))); // NOI18N
        projectLogo.setText("jLabel2");

        projectTitle.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        projectTitle.setText("PRR Organization");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Log In");

        journalPanel.setComponentPopupMenu(journalPopup);
        journalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                journalPanelMouseEntered(evt);
            }
        });

        journals.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        journals.setText("Journals");
        journals.setComponentPopupMenu(journalPopup);
        journals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout journalPanelLayout = new javax.swing.GroupLayout(journalPanel);
        journalPanel.setLayout(journalPanelLayout);
        journalPanelLayout.setHorizontalGroup(
            journalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(journals, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        journalPanelLayout.setVerticalGroup(
            journalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(journalPanelLayout.createSequentialGroup()
                .addComponent(journals, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        bottomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/journalapplication/bgphotodbms.jpeg"))); // NOI18N

        conferencesPanel.setComponentPopupMenu(jPopupMenu1);
        conferencesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                conferencesPanelMouseEntered(evt);
            }
        });

        conferences.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        conferences.setText("Conferences");
        conferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferencesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conferencesPanelLayout = new javax.swing.GroupLayout(conferencesPanel);
        conferencesPanel.setLayout(conferencesPanelLayout);
        conferencesPanelLayout.setHorizontalGroup(
            conferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conferences, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        conferencesPanelLayout.setVerticalGroup(
            conferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conferencesPanelLayout.createSequentialGroup()
                .addComponent(conferences, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        organizations.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        organizations.setText("Organization");
        organizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout organizationsPanelLayout = new javax.swing.GroupLayout(organizationsPanel);
        organizationsPanel.setLayout(organizationsPanelLayout);
        organizationsPanelLayout.setHorizontalGroup(
            organizationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(organizations, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        organizationsPanelLayout.setVerticalGroup(
            organizationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizationsPanelLayout.createSequentialGroup()
                .addComponent(organizations, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        articles.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        articles.setText("Articles");
        articles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout articlesPanelLayout = new javax.swing.GroupLayout(articlesPanel);
        articlesPanel.setLayout(articlesPanelLayout);
        articlesPanelLayout.setHorizontalGroup(
            articlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(articlesPanelLayout.createSequentialGroup()
                .addComponent(articles, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        articlesPanelLayout.setVerticalGroup(
            articlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(articlesPanelLayout.createSequentialGroup()
                .addComponent(articles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomImage, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(journalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(conferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(articlesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(organizationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(projectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(createButton)
                                .addComponent(loginButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(projectTitle)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(journalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(conferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(articlesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(organizationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomImage, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        bottomImage.setBorder(new StraightBorder(2,Color.black));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void journalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalsActionPerformed
        // TODO add your handling code here:
        new Journals().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_journalsActionPerformed

    private void articlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articlesActionPerformed

    private void organizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationsActionPerformed

    private void journalPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_journalPanelMouseEntered
        // TODO add your handling code here:
        journalPopup.show(journals, 0, 36);
        //int x = evt.getX();
       // int y = evt.getY();
       // System.out.println("Hi"+ x+ y);
    }//GEN-LAST:event_journalPanelMouseEntered

    private void conferencesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conferencesPanelMouseEntered
        // TODO add your handling code here:
        jPopupMenu1.show(journals, 142, 36);
        System.out.println(evt.getX());
    }//GEN-LAST:event_conferencesPanelMouseEntered

    private void conferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferencesActionPerformed
        // TODO add your handling code here:
        new Conferences().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_conferencesActionPerformed
    private void setupPopupMenu() {
       // jPopupMenu2 = new javax.swing.JPopupMenu();
        //jMenuItem1 = new javax.swing.JMenuItem("Item 1");
        //jMenuItem2 = new javax.swing.JMenuItem("Item 2");
        //jPopupMenu2.add(jMenuItem1);
       // jPopupMenu2.add(jMenuItem2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton articles;
    private javax.swing.JPanel articlesPanel;
    private javax.swing.JLabel bottomImage;
    private javax.swing.JButton conferences;
    private javax.swing.JPanel conferencesPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel journalPanel;
    private javax.swing.JPopupMenu journalPopup;
    private javax.swing.JButton journals;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton organizations;
    private javax.swing.JPanel organizationsPanel;
    private javax.swing.JLabel projectLogo;
    private javax.swing.JLabel projectTitle;
    // End of variables declaration//GEN-END:variables


}
